services:
  - type: web
    name: ahoy-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 10000
